/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;

import database.SaveImageDB;
import database.service;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.event.ListSelectionEvent;
import org.apache.commons.io.FileUtils;
/**
 *
 * @author AtlantisSeeker
 */
public class PenjualGui extends javax.swing.JFrame {

    /**
     * Creates new form JFrameDesign
     */
    service service1;
    PenjualTableModel contohTableModel1;
    File file;
    JFileChooser jfc;
    public PenjualGui() throws SQLException {
        SaveImageDB.init();
        initComponents();
        initTable();
    }
    
    private void initTable() throws SQLException{
        jTableItem.getSelectionModel().addListSelectionListener((ListSelectionEvent e) -> {
            try{
                int row = jTableItem.getSelectedRow();
                PenjualData contoh1 = contohTableModel1.findOne(row);
                
                Toolkit toolkit = Toolkit.getDefaultToolkit();
                
                String path = new  File(".").getCanonicalPath();
                Image image = toolkit.getImage(path+"/image/"+contoh1.getImage());
                Image imagedResized=image.getScaledInstance(252, 289, Image.SCALE_DEFAULT);
                ImageIcon icon = new ImageIcon(imagedResized);
                tempatGambar.setIcon(icon);
            } catch(IOException ex){
                Logger.getLogger(PenjualGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        service1=SaveImageDB.getservice();
        contohTableModel1 = new PenjualTableModel(service1.findAll());
        jTableItem.setModel(contohTableModel1);
    }
    
    public String isi_txt(){
        return this.jTextFieldTitle.getText();
    }
        
        
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollpane1 = new javax.swing.JScrollPane();
        jTableItem = new javax.swing.JTable();
        gambarItem = new javax.swing.JLabel();
        jTextFieldTitle = new javax.swing.JTextField();
        pilihGambar = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        tempatGambar = new javax.swing.JLabel();
        jButtonHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollpane1.setViewportView(jTableItem);

        getContentPane().add(jScrollpane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 80, -1, 276));

        gambarItem.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        gambarItem.setText("Gambar Item");
        getContentPane().add(gambarItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 25, -1, -1));

        jTextFieldTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTitleActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 369, 244, -1));

        pilihGambar.setText("Pilih gambar");
        pilihGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihGambarActionPerformed(evt);
            }
        });
        getContentPane().add(pilihGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, -1));

        tempatGambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(tempatGambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 54, 252, 289));

        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTitleActionPerformed

    private void pilihGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihGambarActionPerformed
        jfc=new JFileChooser();
        if(jfc.showOpenDialog(tempatGambar)==JFileChooser.APPROVE_OPTION){
            Toolkit toolkit=Toolkit.getDefaultToolkit();
            Image image=toolkit.getImage(jfc.getSelectedFile().getAbsolutePath());
            Image imagedResized=image.getScaledInstance(252, 289, Image.SCALE_DEFAULT);
            ImageIcon imageIcon=new ImageIcon(imagedResized);
            
            tempatGambar.setIcon(imageIcon);
            gambarItem.setText(jfc.getSelectedFile().getName());
            
            file=new File(jfc.getSelectedFile().getPath()); // file untuk dikopi
        }
    }//GEN-LAST:event_pilihGambarActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        PenjualData contoh1=new PenjualData();
        contoh1.setTitle(jTextFieldTitle.getText());
        contoh1.setImage(gambarItem.getText());
        service1.save(contoh1);
        contohTableModel1.save(contoh1);
        try {
            String path=new File(".").getCanonicalPath();
            FileUtils.copyFileToDirectory(file, new File(path+"/image")); //copy file ke folder image
        } catch (IOException ex) {
            Logger.getLogger(PenjualGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new PenjualGui().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(PenjualGui.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gambarItem;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JScrollPane jScrollpane1;
    private javax.swing.JTable jTableItem;
    private javax.swing.JTextField jTextFieldTitle;
    private javax.swing.JButton pilihGambar;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel tempatGambar;
    // End of variables declaration//GEN-END:variables
}
