/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author AtlantisSeeker
 */
public class Kategori extends javax.swing.JFrame {

    /**
     * Creates new form Kategori
     */
    public String kategori;
    public Kategori(String kategori) {
        this.kategori = kategori;
        initComponents();
        add(Buku);
        Buku.setVisible(true);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Buku = new javax.swing.JPanel();
        BlanjaaBTN = new javax.swing.JLabel();
        CloseBTN = new javax.swing.JLabel();
        MinBTN = new javax.swing.JLabel();
        CartBTN = new javax.swing.JLabel();
        AkunBTN = new javax.swing.JLabel();
        LogoutBTN = new javax.swing.JLabel();
        BlackBar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Buku.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlanjaaBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BlanjaaBTNMouseClicked(evt);
            }
        });
        Buku.add(BlanjaaBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 170, 50));

        CloseBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Close Button.png"))); // NOI18N
        Buku.add(CloseBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 0, 40, 30));

        MinBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Min Button.png"))); // NOI18N
        Buku.add(MinBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 40, 30));

        CartBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/CART BUTTON.png"))); // NOI18N
        CartBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CartBTNMouseClicked(evt);
            }
        });
        Buku.add(CartBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, 50, 40));

        AkunBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/AKUN BUTTON.png"))); // NOI18N
        AkunBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AkunBTNMouseClicked(evt);
            }
        });
        Buku.add(AkunBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 20, 40, 40));

        LogoutBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/LOGOUT BUTTON.png"))); // NOI18N
        LogoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBTNMouseClicked(evt);
            }
        });
        Buku.add(LogoutBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 20, 40, 40));

        BlackBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Artboard 13.png"))); // NOI18N
        BlackBar.setText("jLabel1");
        Buku.add(BlackBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/" + kategori + ".png")));
        jLabel6.setText("jLabel2");
        Buku.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Buku, javax.swing.GroupLayout.PREFERRED_SIZE, 1301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 801, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Buku, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlanjaaBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BlanjaaBTNMouseClicked
//        jPanel2.setVisible(false);
//        jPanel1.setVisible(true);
//        Elektronik.setVisible(false);
//        Olahraga.setVisible(false);
//        Fashion.setVisible(false);
//        Buku.setVisible(false);
//        Rumahtangga.setVisible(false);
//        MyAkun.setVisible(false);
//        MyCart.setVisible(false);
        HalamanUtama h = new HalamanUtama();
        h.setVisible(true);
        
    }//GEN-LAST:event_BlanjaaBTNMouseClicked

    private void CartBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CartBTNMouseClicked
//        jPanel2.setVisible(false);
//        jPanel1.setVisible(false);
//        Elektronik.setVisible(false);
//        Olahraga.setVisible(false);
//        Fashion.setVisible(false);
//        Buku.setVisible(false);
//        Rumahtangga.setVisible(false);
//        MyAkun.setVisible(false);
//        MyCart.setVisible(true);
    }//GEN-LAST:event_CartBTNMouseClicked

    private void AkunBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AkunBTNMouseClicked
//        jPanel2.setVisible(false);
//        jPanel1.setVisible(false);
//        Elektronik.setVisible(false);
//        Olahraga.setVisible(false);
//        Fashion.setVisible(false);
//        Buku.setVisible(false);
//        Rumahtangga.setVisible(false);
//        MyAkun.setVisible(true);
//        MyCart.setVisible(false);
    }//GEN-LAST:event_AkunBTNMouseClicked

    private void LogoutBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBTNMouseClicked
//        LogoutPopUp.setVisible(true);
    }//GEN-LAST:event_LogoutBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kategori("Buku").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AkunBTN;
    private javax.swing.JLabel BlackBar;
    private javax.swing.JLabel BlanjaaBTN;
    private javax.swing.JPanel Buku;
    private javax.swing.JLabel CartBTN;
    private javax.swing.JLabel CloseBTN;
    private javax.swing.JLabel LogoutBTN;
    private javax.swing.JLabel MinBTN;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
